/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsDate } from "class-validator";
import { AttendanceUpdateManyWithoutStudentsInput } from "./AttendanceUpdateManyWithoutStudentsInput";
import { Type } from "class-transformer";
import { ExamUpdateManyWithoutStudentsInput } from "./ExamUpdateManyWithoutStudentsInput";
import { ParentWhereUniqueInput } from "../../parent/base/ParentWhereUniqueInput";
import { ReportsUpdateManyWithoutStudentsInput } from "./ReportsUpdateManyWithoutStudentsInput";
import { SchoolFeesUpdateManyWithoutStudentsInput } from "./SchoolFeesUpdateManyWithoutStudentsInput";

@InputType()
class StudentUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AttendanceUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => AttendanceUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => AttendanceUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  attendances?: AttendanceUpdateManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  classField?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => ExamUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => ExamUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => ExamUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  exams?: ExamUpdateManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => ParentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ParentWhereUniqueInput)
  @IsOptional()
  @Field(() => ParentWhereUniqueInput, {
    nullable: true,
  })
  parent?: ParentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReportsUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => ReportsUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => ReportsUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  reportsItems?: ReportsUpdateManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => SchoolFeesUpdateManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => SchoolFeesUpdateManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => SchoolFeesUpdateManyWithoutStudentsInput, {
    nullable: true,
  })
  schoolFeesItems?: SchoolFeesUpdateManyWithoutStudentsInput;
}

export { StudentUpdateInput as StudentUpdateInput };
